# Generated by Django 5.0.8 on 2024-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("Flight_number", models.CharField(max_length=100)),
                ("start_location", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("food_service", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("seats", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
